import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";

export const metadata = {
  title: "LWS Kitchen - Food Blog and Recipes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body class="bg-white">
        <Header />
        <main class="container mx-auto px-4 mt-[100px]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
